name: 'Docker build and push image'
description: 'Builds and publishes a docker image'
inputs:
  registry:
    description: 'Registry Url'
    required: false
    default: ghcr.io
  user:
    description: 'User Docker login'
    required: true
  password:
    description: 'Password Docker login'
    required: true
  context:
    description: 'Context for Dockerfile'
    required: false
    default: .
  dockerfile:
    description: 'Path for Dockerfile'
    required: false
    default: Dockerfile
  platforms:
    description: 'Container platforms'
    required: false
    default: 'linux/amd64,linux/arm64'
    
runs:
  using: "composite"
  steps:

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.user }}
        password: ${{ inputs.password }}

    - name: Extract metadata (tags, labels) for Docker
      if: ${{ inputs.onlyDevImage == 'false' }}
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ github.repository }}

      # Multiplatform builds
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        file: ${{ inputs.dockerfile }}
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
